### PR TITLE
set proxy

### PR DESCRIPTION
**Pull request by David-Turbert**

### CODE REVIEW

**Comment by matteodem** [comment]
Thanks! Can you please elaborate for what the http_proxy can be used? Maybe also state that in the README.md

**Comment by David-Turbert** [comment]
it is because i used meteor in a company with an http proxy and it block all connection who don't passed by it. And when i launch "orion create appName" it work but the folder was empty.

**Comment by matteodem** [comment]
Then I think this needs to be in the orion-cli repository.

**Comment by matteodem** [comment]
I will close this PR and add it to the orion-cli repository. Thank you

**Pull request closed without merging**
